export default [{
  path: '/',
  name: 'main',
  component: 'Index'
}, {
  path: '/login',
  name: 'login',
  component: 'Login'
}, {
  path: '/profile',
  name: 'profile',
  component: 'Profile'
}, {
  path: '/profile-create',
  name: 'profile-create',
  component: 'ProfileCreate'
}, {
  path: '/users/:id',
  name: 'user',
  component: 'User'
}, {
  path: '/resources/:id',
  name: 'resource',
  component: 'Resource'
}, {
  path: '/resource-create',
  name: 'resource-create',
  component: 'ResourceCreate'
}, {
  path: '/filesystem',
  name: 'filesystem',
  component: 'Filesystem'
}, {
  path: '/layouts/:id',
  name: 'layout',
  component: 'Layout'
}, {
  path: '/layout-create',
  name: 'layout-create',
  component: 'LayoutCreate'
}, {
  path: '/layouts',
  name: 'layouts',
  component: 'Layouts'
}, {
  path: '/fields',
  name: 'fields',
  component: 'Fields'
}, {
  path: '/fields/:id',
  name: 'field',
  component: 'Field'
}, {
  path: '/field-create',
  name: 'field-create',
  component: 'FieldCreate'
}, {
  path: '/users',
  name: 'users',
  component: 'Users'
}]
